### ISSUE TITLE
Solution git doesn't correspond to the readme. 

### ISSUE THREAD

**Issue by IngridWong0715** [learn-co-curriculum/js-dom-and-events-acting-on-events-lab#1]
Solution page is on about "creating a form that adds Scuber employees" whereas the readme is on dodger

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
