### ISSUE TITLE
Error with the tests.

### ISSUE THREAD

**Issue by tech-chieftain** [learn-co-curriculum/js-dom-and-events-acting-on-events-lab#2]
Running learn-test on the IDE returns an error 
[ js-dom-and-events-acting-on-events-lab-re-coded-yemen-2018/node_modules/mocha/lib/utils.js:634 
new Error("cannot resolve path (or pattern) '" + path + "'"); ]

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @tech-chieftain.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
