### ISSUE TITLE
Tests Don't Match README

### ISSUE THREAD

**Issue by Hector-Ariceaga** [learn-co-curriculum/js-dom-and-events-acting-on-events-lab#3]
Tests are looking for the following functions: retrieveEmployeeInformation(), addNewElementAsLi(), addNewLiOnClick(), clearEmployeeListOnLinkClick(). README has last two functions required in index.js listed as retrieveEmployeeInformation().

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Hector-Ariceaga.

We have fixed the readme to correctly display the four functions being tested and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
