### ISSUE TITLE
Incorrect test description in readme

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-dom-and-events-acting-on-events-lab#4]
This test as listed in the readme has the same description as the first test in the readme:
"addNewLiOnClick(): This retrieves the employee information from the input."

Actually, the addNewLiOnClick() test is looking for the following:
- adds the employee name as an li element on click
- clears the input value

Please update the readme as this is very confusing.

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
